# -*- coding: utf-8 -*-
"""Project :4 Rock,paper,scissors Python Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ycdD8JSAF1PE4LClTdo5kNAYGRrZ9iBf
"""

import random
choices = ["rock", "paper", "scissors"]

user_choice = input("Enter rock, paper or scissors:").lower()
computer_choice = random.choice(choices)

print(f"You chose: {user_choice}")
print(f"Computer chose: {computer_choice}")

if user_choice == computer_choice:
  print("Its Tie!")
elif (user_choice == "rock" and computer_choice == "scissor") or\
     (user_choice == "scissors" and computer_choice == "paper")or\
     (user_choice == "paper" and computer_choice == "rock"):
  print("You Win!")
else:
  print("Computer Win")